'use client';
import type { CredentialTemplate } from '@/@types/templates';
import { useCustomTemplates } from './useCustomTemplates';

export function useCredentialTemplates() {
  const { customTemplates, saveTemplate, deleteTemplate } = useCustomTemplates();

  const builtIn: CredentialTemplate[] = [
    {
      id: 'impacta-certificate',
      title: 'Impacta Certificate',
      description: 'Certificate template for BAF Impacta Bootcamp.',
      vcType: 'ImpactaCertificateCredential',
      fields: [
        {
          key: 'holderName',
          label: 'Holder Name',
          type: 'text',
          required: true,
          placeholder: 'Full name',
        },
      ],
    },
    {
      id: 'escrow',
      title: 'Escrow',
      description: 'Programmable escrow credential linked to Trustless Work.',
      vcType: 'EscrowCredential',
      iconSrc: '/tw.png',
      fields: [
        {
          key: 'subject',
          label: 'Subject DID',
          type: 'did',
          required: true,
          placeholder: 'Wallet (G...) – we derive DID',
        },
        { key: 'escrowId', label: 'Escrow ID', type: 'text', required: true },
        { key: 'role', label: 'Role', type: 'text', required: true, placeholder: 'payer | payee' },
        { key: 'asset', label: 'Asset', type: 'text', required: true, placeholder: 'USDC' },
        { key: 'amount', label: 'Amount', type: 'number', required: true },
        { key: 'project', label: 'Project', type: 'text', required: false },
        { key: 'issueDate', label: 'Issue Date', type: 'date', required: true },
        { key: 'expirationDate', label: 'Expiration Date', type: 'date' },
      ],
    },
    {
      id: 'contributions',
      title: 'Contributions',
      description: 'Contributions count to a specific project.',
      vcType: 'ContributionsCredential',
      iconSrc: '/gf.png',
      fields: [
        {
          key: 'subject',
          label: 'Subject DID',
          type: 'did',
          required: true,
          placeholder: 'Wallet (G...) – we derive DID',
        },
        { key: 'projectName', label: 'Project Name', type: 'text', required: true },
        { key: 'contributionsCount', label: 'Contributions Count', type: 'number', required: true },
        { key: 'lastContributionDate', label: 'Last Contribution', type: 'date' },
        { key: 'issueDate', label: 'Issue Date', type: 'date', required: true },
        { key: 'expirationDate', label: 'Expiration Date', type: 'date' },
      ],
    },
    {
      id: 'membership',
      title: 'Membership',
      description: 'Membership or subscription credential.',
      vcType: 'MembershipCredential',
      fields: [
        {
          key: 'subject',
          label: 'Subject DID',
          type: 'did',
          required: true,
          placeholder: 'Wallet (G...) – we derive DID',
        },
        { key: 'organization', label: 'Organization', type: 'text', required: true },
        { key: 'level', label: 'Level', type: 'text', required: true, placeholder: 'Gold' },
        { key: 'issueDate', label: 'Start Date', type: 'date', required: true },
        { key: 'expirationDate', label: 'End Date', type: 'date' },
      ],
    },
    {
      id: 'employee_badge',
      title: 'Employee Badge',
      description: 'Employment credential for internal use.',
      vcType: 'EmployeeCredential',
      fields: [
        {
          key: 'subject',
          label: 'Subject DID',
          type: 'did',
          required: true,
          placeholder: 'Wallet (G...) – we derive DID',
        },
        { key: 'company', label: 'Company', type: 'text', required: true },
        { key: 'role', label: 'Role', type: 'text', required: true },
        { key: 'issueDate', label: 'Issue Date', type: 'date', required: true },
        { key: 'expirationDate', label: 'Expiration Date', type: 'date' },
      ],
    },
    {
      id: 'course_certificate',
      title: 'Course Certificate',
      description: 'Credential for course completion.',
      vcType: 'CourseCertificateCredential',
      fields: [
        {
          key: 'subject',
          label: 'Subject DID',
          type: 'did',
          required: true,
          placeholder: 'Wallet (G...) – we derive DID',
        },
        { key: 'courseName', label: 'Course Name', type: 'text', required: true },
        { key: 'provider', label: 'Provider', type: 'text', required: true },
        { key: 'issueDate', label: 'Completion Date', type: 'date', required: true },
        { key: 'expirationDate', label: 'Expiration Date', type: 'date' },
      ],
    },
    {
      id: 'event_attendance',
      title: 'Event Attendance',
      description: 'Credential for event or conference attendance.',
      vcType: 'EventAttendanceCredential',
      fields: [
        {
          key: 'subject',
          label: 'Subject DID',
          type: 'did',
          required: true,
          placeholder: 'Wallet (G...) – we derive DID',
        },
        { key: 'eventName', label: 'Event Name', type: 'text', required: true },
        { key: 'eventDate', label: 'Event Date', type: 'date', required: true },
        { key: 'location', label: 'Location', type: 'text', required: true },
        { key: 'role', label: 'Role', type: 'text', required: false, placeholder: 'Attendee' },
        { key: 'organizer', label: 'Organizer', type: 'text', required: false },
        { key: 'issueDate', label: 'Issue Date', type: 'date', required: true },
        { key: 'expirationDate', label: 'Expiration Date', type: 'date' },
      ],
    },
    {
      id: 'payment_receipt',
      title: 'Payment Receipt',
      description: 'Credential for payment or transaction receipts.',
      vcType: 'PaymentReceiptCredential',
      fields: [
        {
          key: 'subject',
          label: 'Subject DID',
          type: 'did',
          required: true,
          placeholder: 'Wallet (G...) – we derive DID',
        },
        { key: 'merchant', label: 'Merchant', type: 'text', required: true },
        { key: 'invoiceId', label: 'Invoice ID', type: 'text', required: true },
        { key: 'amount', label: 'Amount', type: 'number', required: true },
        { key: 'asset', label: 'Asset', type: 'text', required: true, placeholder: 'USDC' },
        { key: 'paidAt', label: 'Payment Date', type: 'date', required: true },
        { key: 'txHash', label: 'Transaction Hash', type: 'text', required: false },
        { key: 'issueDate', label: 'Issue Date', type: 'date', required: true },
      ],
    },
    {
      id: 'kyc_verification',
      title: 'KYC Verification',
      description: 'Identity verification credential.',
      vcType: 'KYCVerificationCredential',
      fields: [
        {
          key: 'subject',
          label: 'Subject DID',
          type: 'did',
          required: true,
          placeholder: 'Wallet (G...) – we derive DID',
        },
        { key: 'fullName', label: 'Full Name', type: 'text', required: true },
        { key: 'country', label: 'Country', type: 'text', required: true },
        {
          key: 'verificationLevel',
          label: 'Verification Level',
          type: 'text',
          required: true,
          placeholder: 'Basic | Advanced | Full',
        },
        { key: 'verifiedBy', label: 'Verified By', type: 'text', required: true },
        { key: 'issueDate', label: 'Issue Date', type: 'date', required: true },
        { key: 'expirationDate', label: 'Expiration Date', type: 'date' },
      ],
    },
    {
      id: 'access_pass',
      title: 'Access Pass',
      description: 'Credential granting access to resources or services.',
      vcType: 'AccessPassCredential',
      fields: [
        {
          key: 'subject',
          label: 'Subject DID',
          type: 'did',
          required: true,
          placeholder: 'Wallet (G...) – we derive DID',
        },
        { key: 'resource', label: 'Resource', type: 'text', required: true },
        {
          key: 'permission',
          label: 'Permission',
          type: 'text',
          required: true,
          placeholder: 'read | write | admin',
        },
        { key: 'scope', label: 'Scope', type: 'text', required: false },
        { key: 'issueDate', label: 'Issue Date', type: 'date', required: true },
        { key: 'expirationDate', label: 'Expiration Date', type: 'date' },
      ],
    },
    {
      id: 'skill_badge',
      title: 'Skill Badge',
      description: 'Credential recognizing a specific skill or competency.',
      vcType: 'SkillBadgeCredential',
      fields: [
        {
          key: 'subject',
          label: 'Subject DID',
          type: 'did',
          required: true,
          placeholder: 'Wallet (G...) – we derive DID',
        },
        { key: 'skill', label: 'Skill', type: 'text', required: true },
        {
          key: 'level',
          label: 'Level',
          type: 'text',
          required: true,
          placeholder: 'Beginner | Intermediate | Expert',
        },
        { key: 'issuer', label: 'Issuer', type: 'text', required: true },
        { key: 'evidenceUrl', label: 'Evidence URL', type: 'text', required: false },
        { key: 'issueDate', label: 'Issue Date', type: 'date', required: true },
      ],
    },
    {
      id: 'warranty',
      title: 'Warranty',
      description: 'Product warranty or support credential.',
      vcType: 'WarrantyCredential',
      fields: [
        {
          key: 'subject',
          label: 'Subject DID',
          type: 'did',
          required: true,
          placeholder: 'Wallet (G...) – we derive DID',
        },
        { key: 'productName', label: 'Product Name', type: 'text', required: true },
        { key: 'serialNumber', label: 'Serial Number', type: 'text', required: true },
        { key: 'purchaseDate', label: 'Purchase Date', type: 'date', required: true },
        {
          key: 'coverage',
          label: 'Coverage',
          type: 'text',
          required: true,
          placeholder: 'Full | Limited',
        },
        { key: 'issueDate', label: 'Issue Date', type: 'date', required: true },
        { key: 'expirationDate', label: 'Expiration Date', type: 'date' },
      ],
    },
  ];

  const templates: CredentialTemplate[] = [...builtIn, ...customTemplates];

  return { templates, saveTemplate, deleteTemplate };
}
